/* eslint-disable no-useless-escape */

export const goodSRT = `[Script Info]
; Script generated by Aegisub 2.1.8
; http://www.aegisub.org/

[V4+ Styles]
; Missing Format line - this should fail parsing

[Events]
Dialogue: 0,0:02:40.18,0:02:43.52,Default,,0000,0000,0000,,Test subtitle
`;

export const badASSkeys = `[Script Info]
; Script generated by Aegisub 2.1.8
; http://www.aegisub.org/

[V4+ Styles]
; Missing Format line - this should fail parsing

[Events]
Dialogue: 0,0:02:40.18,0:02:43.52,Default,,0000,0000,0000,,Test subtitle
`;
